onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - sharp

overrides:
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  next@>=15.2.0-canary.0 <15.2.6: '>=15.2.6'
  next@>=15.2.0-canary.0 <15.2.7: '>=15.2.7'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
